### ISSUE TITLE
Make install fails

### ISSUE THREAD

**Issue by cedarhillgoods** [kerrickstaley/Chinese-Prestudy#10]
Steps to reproduce:

1. Clone repo
2. make install

$ make install
./package.py
Traceback (most recent call last):
  File "./package.py", line 119, in <module>
    copy_dependencies_from_local()
  File "./package.py", line 104, in copy_dependencies_from_local
    dirpaths.sort(key=lambda p: _path_to_sort_tuple(p))
  File "./package.py", line 104, in <lambda>
    dirpaths.sort(key=lambda p: _path_to_sort_tuple(p))
  File "./package.py", line 93, in _path_to_sort_tuple
    version_tuple = tuple(int(piece) for piece in _extract_version(path).split('.'))
  File "./package.py", line 89, in _extract_version
    return re.search(r'[0-9]+(\.[0-9]+)*', dirname).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
make: *** [Makefile:21: package.zip] Error 1

**Comment by cedarhillgoods** [comment]
I believe this bug is being caused when the dirpaths variable in copy_dependencies_from_local() globs a filepath without any version number in the filename such as 

'/home/sampleuser/.local/lib/python3.7/site-packages/chinesevocablist.egg-link'

rather than 

'/home/sampleuser/.local/lib/python3.7/site-packages/chinesevocablist-0.3.4-py3.7.egg'

When the no-version-number path is fed to the _extract_version() function, the regex search causes the program to crash due to no version numbers embedded within the filename being found.

**Comment by kerrickstaley** [comment]
This should be fixed by 688446c100db2323af21ff1b7a8ce4667c1b03c5 .
