### ISSUE TITLE
add a stop list and ability to customize wordlist

### ISSUE THREAD

**Issue by thinlines** [kerrickstaley/Chinese-Prestudy#13]
I love the idea behind this plugin, but I noticed when I put [this article about Joaquin Phoenix's acceptance speech for *The Joker*][1] into the plugin it wants to add all the words from in the list including simple ones I don't need to study, like 我, for example. A stop list to prevent these words from showing would be helpful to eliminate this problem. I guess I could add a tag and manually delete them, but that seems like work I'd have to do every time I read an article.

[1]: https://ent.sina.com.cn/m/f/2020-02-10/doc-iimxyqvz1679878.shtml?cre=tianyi&mod=pcent&loc=6&r=25&rfunc=86&tj=none&tr=25

The other problem I noticed is that there was only one word in the word list that showed up that I wasn't very familiar with (沮丧), but other unfamiliar words in the article didn't appear, like 主宰 or 脱节. For me, at least, It's possible to guess the meaning without much effort, but that doesn't solve the pronunciation problem. It would be helpful if the user could use a different word list like the HSK5 or 6 to catch more of these less common words.

Maybe a different tool would be more suited to this problem, or just manually looking up characters, but making the reading process as quick as possible is the goal, and this plugin would be ideal for that. At any rate, this plugin is a great idea. Thanks for developing it!

**Comment by kerrickstaley** [comment]
As of the latest version, you can choose to exclude the most common N words, which will help with eliminating common words like 我, but you'll have to play around with the threshold to try to figure out what a good cutoff is that matches your existing vocabulary size. The full list is in [`chinese_vocab_list.yaml`](https://raw.githubusercontent.com/kerrickstaley/Chinese-Vocab-List/master/chinese_vocab_list.yaml) in my [Chinese-Vocab-List](https://github.com/kerrickstaley/Chinese-Vocab-List) project, so you can look though it (try the command `cat chinese_vocab_list.yaml | egrep '^- trad:' | nl`) to figure out a good threshold.

Another approach that should work is simply suspending cards that you aren't interested in learning when they come up for review.

Regarding words like 主宰, this tool is not intended to cover all Chinese words that exist. The idea is that you will learn a core vocabulary of ~3500 words using Anki, and beyond that you will use a dictionary to look up words when you encounter them. This strategy seems to provide a good balance between spending time studying in Anki and spending time reading. The tool supports up to 3988 words currently (which is the number of words in `chinese_vocab_list.yaml`). I may expand this limit in the future (it's not hard but there is a bit of work to do when words have multiple entries in [CC-CEDICT](https://cc-cedict.org/editor/editor.php)) but right now for my personal learning I think 3500 is a good target.

Look at [Chinese Support Redux](https://ankiweb.net/shared/info/1128979221) for a tool that can create flashcards for arbitrary Chinese words.
