### ISSUE TITLE
No 'yaml' named python package as written in setup instructions

### ISSUE THREAD

**Issue by cedarhillgoods** [kerrickstaley/Chinese-Prestudy#9]
I guess the python package name for yaml has changed since the instructions were written?

```
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml 
```

Steps to reproduce bug:

1. Clone repo
2. Run `pip3 install --user chinesevocablist chineseflashcards genanki jieba cached_property pystache yaml` as stated in the setup instructions.

**Comment by kerrickstaley** [comment]
Whups, yeah, the `yaml` module is contained in the [`pyyaml` package](https://pypi.org/project/PyYAML/). Fixed in c66967701f966e6b878611e2ebac98d2ca0db200
